### ISSUE TITLE
请问小马哥《Java项目实战营》课程如何？满意吗？我想报最新一期，希望您能告知！！

### ISSUE THREAD

**Issue by zgkaii** [tanpenggood/geek-training-camp#1]

**Comment by tanpenggood** [comment]
这是小马哥给第0期小伙伴讲的原话：
> 1期重点将自研、开源以及云原生技术整合到项目中，并且使用“最佳实践”优雅地实现或重构项目，简单地说，将功能特性和架构选型最优化。不过，第1期会与第0期在技术细节上小部分重叠，这是要照顾没有过报名0期的小伙伴，从1期就能学。同时，第1期的难度会比0期要小，0期比较注重面试和技术设计和实现，1期偏向技术原理和项目最佳实践，两期相辅相成，在大纲上没有太多变化，毕竟 Java 开发范围有限。我个人建议两期都报，共计6-7月的时间，把这些知识融会贯通，达到弯道超车的目的。
